[package]
name = "clone-tabnews"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serde_json = "1.0.151"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7.18"
topcoat = { git = "https://github.com/tokio-rs/topcoat", rev = "6b7681a" }
